### ISSUE TITLE
NullReference exception with certain XML file in release 0.6.0

### ISSUE THREAD

**Issue by niknas** [JDCain/FG5eXmlToPdf#10]
System.NullReferenceException: Objektreferensen har inte angetts till en instans av ett objekt.
   vid FG5eXmlToPDF.FG5eXml.GenericItemMaker(XElement features) i C:\Source\repos\FG5eXmlToPdf\FG5eXmlToPdf\Fg5eXml.cs:rad 114
   vid FG5eXmlToPDF.FG5eXml.<>c__DisplayClass2_0.<PopulateGenericList>b__0(XElement x) i C:\Source\repos\FG5eXmlToPdf\FG5eXmlToPdf\Fg5eXml.cs:rad 110
   vid System.Collections.Generic.List`1.ForEach(Action`1 action)
   vid FG5eXmlToPDF.FG5eXml.PopulateGenericList(List`1 traitList, List`1 itemList) i C:\Source\repos\FG5eXmlToPdf\FG5eXmlToPdf\Fg5eXml.cs:rad 110
   vid FG5eXmlToPDF.FG5eXml.LoadCharacter(String fileString) i C:\Source\repos\FG5eXmlToPdf\FG5eXmlToPdf\Fg5eXml.cs:rad 21
   vid FG5eXmlToPdf.Console.Program.Main(String[] args)

Ohanterat undantag: System.NullReferenceException: Objektreferensen har inte angetts till en instans av ett objekt.
   vid FG5eXmlToPDF.FG5eXml.GenericItemMaker(XElement features) i C:\Source\repos\FG5eXmlToPdf\FG5eXmlToPdf\Fg5eXml.cs:rad 114
   vid FG5eXmlToPDF.FG5eXml.<>c__DisplayClass2_0.<PopulateGenericList>b__0(XElement x) i C:\Source\repos\FG5eXmlToPdf\FG5eXmlToPdf\Fg5eXml.cs:rad 110
   vid System.Collections.Generic.List`1.ForEach(Action`1 action)
   vid FG5eXmlToPDF.FG5eXml.PopulateGenericList(List`1 traitList, List`1 itemList) i C:\Source\repos\FG5eXmlToPdf\FG5eXmlToPdf\Fg5eXml.cs:rad 110
   vid FG5eXmlToPDF.FG5eXml.LoadCharacter(String fileString) i C:\Source\repos\FG5eXmlToPdf\FG5eXmlToPdf\Fg5eXml.cs:rad 21
   vid FG5eXmlToPdf.Console.Program.Main(String[] args)

[faffner.zip](https://github.com/JDCain/FG5eXmlToPdf/files/1522026/faffner.zip)

**Comment by JDCain** [comment]
Looks like there is a empty block in the traitlist.
`		<traitlist>
			<id-00001>
			</id-00001>
		</traitlist>`
Looking how to handle it.

**Comment by JDCain** [comment]
Fixed in 7c4ed000274e8a3bea2ed28ef1bd5529544c4e6c
